### ISSUE TITLE
Expect open source.

### ISSUE THREAD

**Issue by cskrren** [lmb-freiburg/neural-point-cloud-diffusion#1]

**Comment by pschroeppel** [comment]
Hi, I am currently on vacation, but the code will definitely be open sourced after that.
Best,
Philipp

**Comment by Mike001-wq** [comment]
> Hi, I am currently on vacation, but the code will definitely be open sourced after that. Best, Philipp

This is truly an amazing work! Looking forward to seeing the wonderful code soon.
